### PR TITLE
Compressed Instructions

### PR DESCRIPTION
**Pull request by phoebemeira**
For compressed instruction support

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Review by vembaylosis — APPROVED** [review]

**Review by mjneri — CHANGES_REQUESTED** [review]
> For compressed instruction support

**Review by mjneri — DISMISSED** [review]
test comment 1 2 3 4

**Comment by mjneri** [comment]
123

**Comment by mjneri** [comment]
paano magreview ng pullrequest sa vscode hahaha

**Comment by wwwwww70** [comment]
```diff
diff --git a/Baseline processor/instmem.v b/Baseline processor/instmem.v
index 3552ada..56c26a3 100644
--- a/Baseline processor/instmem.v	
+++ b/Baseline processor/instmem.v	
@@ -11,8 +11,8 @@ module instmem(
 	// Synchronous read
 	wire [10:0] addr_2 = addr[11:1] + 11'd1;
 
-	blk_mem_gen_instmem BLOCKMEM(
-		.clka(~clk),
+	wire [10:0] addr_2 = addr[11:1] + 11'd1;
+
 		.addra({addr[11:1]}),
 		.douta(inst[15:0]),
 		.ena(1'b1),
@@ -20,6 +20,12 @@ module instmem(
 		.addrb({addr_2[10:0]}),
 		.doutb(inst[31:16]),
 		.enb(1'b1)
+		.douta(inst[15:0]),
+		.ena(1'b1),
+		.clkb(~clk),
+		.addrb({addr_2[10:0]}),
+		.doutb(inst[31:16]),
+		.enb(1'b1)
 	);
 
 

```

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
